### ISSUE TITLE
ExpandString as Value Type Not Working

### ISSUE THREAD

**Issue by andoryuu-cloud** [PowerShellCrack/LGPOPSmodule#3]
Looks like ExpandString as a value type is not working:

The following example does not work:
Set-LocalPolicySetting -Path 'HKLM:\Software\Policies\Microsoft\Windows\Safer\CodeIdentifiers\0\Paths\{e080b67a-5988-45e8-a553-72edffcb8f34}' -Name 'ItemData' -Type ExpandString -Value "SomeValue"

The command finishes and there aren't any errors, however, nothing is written in the registry nor in Registry.pol.
It looks like it doesn't even attempt to write to Registry.pol as I locked the file and the command executed nonetheless (other working commands do not finish executing until the file is unlocked).

If I type the exact command but replace ExpandString with String it works:
Set-LocalPolicySetting -Path 'HKLM:\Software\Policies\Microsoft\Windows\Safer\CodeIdentifiers\0\Paths\{e080b67a-5988-45e8-a553-72edffcb8f34}' -Name 'ItemData' -Type String -Value "SomeValue"

Can this be fixed?

**Comment by PowerShellCrack** [comment]
You right. I had to change the LGPO type variable to EXSZ (instead of EXPANDSZ). This should have fixed it

**Comment by andoryuu-cloud** [comment]
Thanks.

However, now the Remove-LocalPolicySetting (in general) seems to be broken.
It looks like it doesn't do anything now, I have the Registry.pol file locked and the Remove-LocalPolicySetting commands finishe nonetheless (nothing is removed or written in Registry.pol).

**Comment by PowerShellCrack** [comment]
I'm not sure I'm tracking the problem. I did make a few changes to that cmdlet as well. I did see an issue with the -Force command (which does registry remove) and I just updated it to resolve that. Please Try it out again

Also can you provide more information like command running with verbose output and screenshot that output? Also if you run -Debug. in the %temp% there will be three files in there base don command ran. Review the lgpo, stdout, stderr files to see where it failed.

**Comment by andoryuu-cloud** [comment]
The issue is now fixed.

I noticed that the remove option actually writes in the Registry.pol to delete the registry persistently rather than remove it completely from Registry.pol. This will remove any settings set after every gpupdate. 
Is there a way to remove the registry and then remove it from Registry.pol as well so that the delete is not persistent?

Thanks

**Comment by PowerShellCrack** [comment]
that's good to hear its working. Currently it does write to registry.pol and is persistent because you're using LGPO to set local policy. I could add NonPersistence parameter which basically doesn't run LGPO, but that's the same as running Remove-ItemProperty. Except of the fact that once local gpo runs again it set the keys again. **That is one of the identified gaps with LGPO is there is no way to set a setting to "not configured" that I'm aware of.** 

I am, however, working on a new cmdlet that may fix this, but it's not ready. The process would be this, it has to output all configured settings, delete the registry.pol. then rebuild and set all the settings back leaving out the keys identified as nonpersistent (aka not configured), then delete the registry keys is they exist. This is because not configured means it the keys would normally stay but can be deleted. 

Is it alright if I close this issue? we can throw this ask in a feature request.

**Comment by andoryuu-cloud** [comment]
That sounds good.

Yes, issue resolved :)
